### ISSUE TITLE
Update fingerprint

### ISSUE THREAD

**Issue by aguys123** [RisenID/HuskySpoof#1]
Thanks to this module, I successfully enabled Circle to Search on my Pixel 6 (Android 14 March update). But I find that its fingerprint still uses the January update, is there any concern in the future?

**Comment by RisenID** [comment]
Ill update fp soon anyway

**Comment by aguys123** [comment]
Ok thx

**Comment by RisenID** [comment]
Done as of https://github.com/RisenID/PixelSpoof/releases/tag/AP1A.240505.005
